import axios from "axios";
import type {
  ClustersResponse,
  HealthResponse,
  InvestigateResponse,
  ProgressResponse,
} from "@/types";
import { insforge } from "@/services/insforge";

// Axios instance shared by all API calls.
// Configure the backend URL via NEXT_PUBLIC_API_BASE_URL (see .env.example).
export const api = axios.create({
  baseURL: process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://localhost:8000",
  timeout: 10_000,
});

// When InsForge is configured the backend requires the signed-in user's
// access token. getValidAccessToken() refreshes it first if it is expiring.
api.interceptors.request.use(async (config) => {
  const token = await insforge?.getHttpClient().getValidAccessToken();
  if (token) {
    config.headers.Authorization = `Bearer ${token}`;
  }
  return config;
});

export async function getHealth(): Promise<HealthResponse> {
  const response = await api.get<HealthResponse>("/health");
  return response.data;
}

// Lists the kubeconfig contexts available on the backend host.
export async function getClusters(): Promise<ClustersResponse> {
  const response = await api.get<ClustersResponse>("/clusters");
  return response.data;
}

// Runs a full cluster investigation. This can take up to ~2 minutes
// (kubectl collection + LLM analysis), hence the long timeout.
// `investigationId` is generated by the caller so it can poll progress
// while this request runs. Pass a kubeconfig context name to investigate a
// specific cluster.
export async function investigate(
  investigationId: string,
  context?: string | null,
): Promise<InvestigateResponse> {
  const response = await api.post<InvestigateResponse>(
    "/investigate",
    { investigation_id: investigationId, context: context ?? null },
    { timeout: 180_000 },
  );
  return response.data;
}

// Polls the progress of an in-flight investigation.
export async function getProgress(
  investigationId: string,
): Promise<ProgressResponse> {
  const response = await api.get<ProgressResponse>(
    `/investigations/${investigationId}/progress`,
  );
  return response.data;
}

// Turns an axios/unknown error into a short, user-readable message.
export function toErrorMessage(error: unknown): string {
  if (axios.isAxiosError(error)) {
    if (error.code === "ECONNABORTED") {
      return "The investigation timed out after 3 minutes. Please try again.";
    }
    if (!error.response) {
      return "Backend unreachable — is it running on :8000?";
    }
    if (error.response.status === 401) {
      return "Your session has expired. Sign out and sign in again.";
    }
    const detail =
      (error.response.data as { detail?: string } | undefined)?.detail;
    return detail ?? `Backend error (HTTP ${error.response.status}).`;
  }
  return error instanceof Error ? error.message : "Unexpected error.";
}
